#!/bin/sh
echo "*****Запуск unit тестов******"
git stash -q --keep-index

./mvnw test
status=$?
if [ $status -ne 0 ]; then
	echo "*****Завершение unit тестов******"
	echo "Тесты не прошли успешно. Отмена push."
	exit 1
fi